services:

  app:
    build: .
    container_name: sit753-app
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo:27017/sit753-devops
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: sit753-mongo
    ports:
      - "27017:27017"
    volumes:
      - sit753_mongo_data:/data/db

volumes:
  sit753_mongo_data: